# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Planit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Planit
	
  pod 'JTAppleCalendar', '~> 7.1'

end
